name: 'Deploy vite app to github pages'
description: 'This action will automate the process of building and deploying a vite app to the gh-pages branch.'
author: 'fechan'
branding:
  color: blue
  icon: code
inputs:
  working-directory:
    description: Working directory for this action
    required: true
runs: 
  using: 'composite'
  steps: 
    - run : npm i --include=dev
      working-directory: ${{ inputs.working-directory }}
      shell: bash
    - run : npm ci --include=dev
      working-directory: ${{ inputs.working-directory }}
      shell: bash
    - run : npx vite build
      working-directory: ${{ inputs.working-directory }}
      shell: bash
    - run : git config user.name github-actions
      working-directory: ${{ inputs.working-directory }}
      shell: bash
    - run : git config user.email github-actions@github.com
      working-directory: ${{ inputs.working-directory }}
      shell: bash
    - run : git --work-tree dist add --all
      working-directory: ${{ inputs.working-directory }}
      shell: bash
    - run : git commit -m "Automatic Deploy action run by github-actions"
      working-directory: ${{ inputs.working-directory }}
      shell: bash
    - run : git push origin HEAD:gh-pages --force
      working-directory: ${{ inputs.working-directory }}
      shell: bash