name: Vite app deployment

on:
  push:
    branches: [ master ]

jobs:
  build:

    permissions:
      contents: write

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Deploy vite app to github pages
      uses: ./.github/actions/deploy-vite-to-ghpages
      with:
        working-directory: ./client
